### ISSUE TITLE
Update mdast to remark

### ISSUE THREAD

**Issue by wooorm** [thoughtbot/hound-mdast#5]
Hey! Just wanted ping and request a name change from mdast to remark. Maybe you’ve already seen it but here’s a list of reasons [why to update](https://github.com/wooorm/remark/releases/tag/3.0.0).

Let me know if I can help! :smile:

**Comment by wooorm** [comment]
Friendly ping: @thorncp!

**Comment by thorncp** [comment]
Hey @wooorm, thanks for the ping! Apparently I forgot to subscribe to notifications on this repo O_o

Are there any API changes that come with the new major version, or do we just need to make the name change and update dependencies?

**Comment by wooorm** [comment]
Hey @thorncp, no problem.

There are no API changes, but there are:

*   Changes in how markdown is parsed/compiled (possibly still with some bugs but much has already been fixed);
*   Renamed plug-ins and configuration files (`.remarkrc`, `.remarkignore`, and `remarkConfig` in `package.json`).

All in all, I don’t think your code will need changes other than s/mdast/remark/.

P.S. You could use remark CLIs `configuration` detecting methods, [here’s how it’s implemented in AtomLinter/linter-markdown](https://github.com/AtomLinter/linter-markdown/blob/389ee3cd0e29d5a04e4fdc369be5de052207af9e/lib/index.js#L101-L104)

**Comment by wooorm** [comment]
:+1:
